"""add image_id in imagePostItem

Revision ID: 0c245df07d5c
Revises: b7ef2d5100f6
Create Date: 2024-09-15 12:12:02.719701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c245df07d5c'
down_revision: Union[str, None] = 'b7ef2d5100f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('image_post_item', sa.Column('image_id', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'image_post_item', ['image_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_post_item', type_='unique')
    op.drop_column('image_post_item', 'image_id')
    # ### end Alembic commands ###
