"""changes in user and about table

Revision ID: 20b4555dc60b
Revises: a8bfe3faed14
Create Date: 2024-09-12 15:20:10.924396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20b4555dc60b'
down_revision: Union[str, None] = 'a8bfe3faed14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verfied', sa.Boolean(), nullable=True))
    op.drop_index('phone_number', table_name='user')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('phone_number', 'user', ['phone_number'], unique=True)
    op.drop_column('user', 'is_verfied')
    # ### end Alembic commands ###
