"""updated chat table

Revision ID: 4eff1954cba8
Revises: 4e5b5a5ac966
Create Date: 2024-09-15 22:25:00.995172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eff1954cba8'
down_revision: Union[str, None] = '4e5b5a5ac966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('message', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'message')
    # ### end Alembic commands ###
