"""deleted post item and add textpostitem and imagepostitem

Revision ID: 528d0ea5ba66
Revises: 7508ae85a549
Create Date: 2024-09-14 13:45:58.281344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '528d0ea5ba66'
down_revision: Union[str, None] = '7508ae85a549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_post_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_post_item_id'), 'image_post_item', ['id'], unique=False)
    op.create_table('text_post_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_post_item_id'), 'text_post_item', ['id'], unique=False)
    op.drop_index('ix_postItem_id', table_name='postitem')
    op.drop_table('postitem')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postitem',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='postitem_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_postItem_id', 'postitem', ['id'], unique=False)
    op.drop_index(op.f('ix_text_post_item_id'), table_name='text_post_item')
    op.drop_table('text_post_item')
    op.drop_index(op.f('ix_image_post_item_id'), table_name='image_post_item')
    op.drop_table('image_post_item')
    # ### end Alembic commands ###
