"""updated user with srecert ket

Revision ID: 53b9fc002185
Revises: 13d85884fca2
Create Date: 2024-09-16 10:45:16.598504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53b9fc002185'
down_revision: Union[str, None] = '13d85884fca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'secret_key',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'secret_key',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###
