"""deleted text post item and updated imagepost and post 

Revision ID: 56507925decb
Revises: 528d0ea5ba66
Create Date: 2024-09-14 22:31:44.994348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56507925decb'
down_revision: Union[str, None] = '528d0ea5ba66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_text_post_item_id', table_name='text_post_item')
    op.drop_table('text_post_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_post_item',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='text_post_item_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_text_post_item_id', 'text_post_item', ['id'], unique=False)
    # ### end Alembic commands ###
