"""change in post and post item ->changed the files 

Revision ID: 6c81ed6488f3
Revises: 0f869455658f
Create Date: 2024-09-14 10:39:02.040492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c81ed6488f3'
down_revision: Union[str, None] = '0f869455658f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_item', 'post_type',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('post_item', 'post_content',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_item', 'post_content',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('post_item', 'post_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
