"""inserted about table and sight change in user table

Revision ID: 6f2e66da9e71
Revises: 9d5040867462
Create Date: 2024-09-12 14:06:09.008157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6f2e66da9e71'
down_revision: Union[str, None] = '9d5040867462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_status', sa.String(length=10), nullable=False),
    sa.Column('bio', sa.String(length=250), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_id'), 'about', ['id'], unique=False)
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.drop_column('user', 'account_status')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'is_verfied')
    op.drop_column('user', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('is_verfied', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('bio', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('user', sa.Column('account_status', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('user', 'is_verified')
    op.drop_index(op.f('ix_about_id'), table_name='about')
    op.drop_table('about')
    # ### end Alembic commands ###
