"""change in post and post item ->change the names 

Revision ID: 7508ae85a549
Revises: 6c81ed6488f3
Create Date: 2024-09-14 11:09:15.535004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7508ae85a549'
down_revision: Union[str, None] = '6c81ed6488f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postItem_id'), 'postItem', ['id'], unique=False)
    op.drop_index('ix_post_item_id', table_name='post_item')
    op.drop_table('post_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_item',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('post_content', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_item_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_post_item_id', 'post_item', ['id'], unique=False)
    op.drop_index(op.f('ix_postItem_id'), table_name='postItem')
    op.drop_table('postItem')
    # ### end Alembic commands ###
