"""user model updated with username,account_status,bio,ect

Revision ID: 9d5040867462
Revises: 8e648c412614
Create Date: 2024-09-12 13:46:43.571628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9d5040867462'
down_revision: Union[str, None] = '8e648c412614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(length=10), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('account_status', sa.String(length=10), nullable=False))
    op.add_column('user', sa.Column('bio', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('is_verfied', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('user', 'full_name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['phone_number'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'is_verfied')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'account_status')
    op.drop_column('user', 'username')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
