"""add is_active in imagepostitem and delted is_active in post table

Revision ID: b7ef2d5100f6
Revises: 4893ae61e304
Create Date: 2024-09-15 12:05:31.869271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7ef2d5100f6'
down_revision: Union[str, None] = '4893ae61e304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_post_item', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('post', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('image_post_item', 'is_active')
    # ### end Alembic commands ###
