"""changes in about add profile photo

Revision ID: ca840013dc56
Revises: cab21746429b
Create Date: 2024-09-13 16:10:00.181436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca840013dc56'
down_revision: Union[str, None] = 'cab21746429b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('profile_photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about', 'profile_photo')
    # ### end Alembic commands ###
