"""updated image table

Revision ID: cfdbce0732b8
Revises: 53b9fc002185
Create Date: 2024-09-17 11:11:21.363091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cfdbce0732b8'
down_revision: Union[str, None] = '53b9fc002185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image_post_item', 'image_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               autoincrement=False)
    op.drop_index('image_id', table_name='image_post_item')
    op.drop_index('ix_image_post_item_id', table_name='image_post_item')
    op.drop_column('image_post_item', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_post_item', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_image_post_item_id', 'image_post_item', ['id'], unique=False)
    op.create_index('image_id', 'image_post_item', ['image_id'], unique=True)
    op.alter_column('image_post_item', 'image_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###
