"""updated user with srecert ket

Revision ID: e8ee29f8970f
Revises: 4eff1954cba8
Create Date: 2024-09-16 10:10:54.474805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ee29f8970f'
down_revision: Union[str, None] = '4eff1954cba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('srecert_key', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'srecert_key')
    # ### end Alembic commands ###
